.travis.yml, buildout.cfg, openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/utils.py
https://github.com/openprocurement/openprocurement.api/pull/64
https://github.com/openprocurement/openprocurement.chronograph/pull/6
https://github.com/openprocurement/openprocurement.tender.openua/pull/3
=> New chronograph mechanism of auction planning and replanning

openprocurement/tender/openeu/tests/contract.py
Непробні тести видалено, а тести для перевірки методу patch додано
=> update test for contract

openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/tests/base.py
для цих змін потрібна буде міграція
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/9)
=> added required deliveryAddress and deliveryDate fields

openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/tests/base.py
Reverts openprocurement/openprocurement.tender.openeu#9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/12)
=> Revert "added required deliveryAddress and deliveryDate fields"

openprocurement/tender/openeu/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/14)
=> MEDT -> NONE

openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/tests/base.py, openprocurement/tender/openeu/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/15)
=> set required endDate

openprocurement/tender/openeu/tests/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/16)
=> unittests for datesigned

docs/source/standard/item.rst, docs/source/standard/organization.rst, docs/source/standard/util.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/17)
=> added required fields to docs in eu

buildout.cfg, openprocurement/tender/openeu/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/21)
=> Parallel testing with nose

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/22)
=> Change branch to master

openprocurement/tender/openeu/tests/award.py, openprocurement/tender/openeu/tests/bid.py, openprocurement/tender/openeu/tests/complaint.py, openprocurement/tender/openeu/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/23)
=> Add tests transfer_token for tender, bid, complaint and award complaint

openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/views/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/24)
=> Can`t change pre-qualification status to standstill with unresolved complaints

buildout.cfg, openprocurement/tender/openeu/tests/contract.py
Додав тести для перевірки можливості об'єднання контрактів.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/26)
=> Додав тести для об'єднання контрактів

buildout.cfg, openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/views/qualification_complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/29)
=> Add transfer for qualification_complaint for task Qualification complaint transfer

openprocurement/tender/openeu/tests/bid.py, openprocurement/tender/openeu/views/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/31)
=> Fix deleted bid can be restored

docs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/35)
=> Update award after complaints were switched in terminal status

openprocurement/tender/openeu/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/39)
=> TENDERING_DAYS import

openprocurement/tender/openeu/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/40)
=> import from declaration place

openprocurement/tender/openeu/views/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/41)
=> Validators refactoring in tender view

.gitignore, openprocurement/tender/openeu/includeme.py, openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/subscribers.py, openprocurement/tender/openeu/tests/auction.py, openprocurement/tender/openeu/tests/base.py, openprocurement/tender/openeu/tests/tests.ini, openprocurement/tender/openeu/views/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/45)
=> Add tender initialization event handler

openprocurement/tender/openeu/validation.py, openprocurement/tender/openeu/views/bid.py, openprocurement/tender/openeu/views/qualification.py, openprocurement/tender/openeu/views/qualification_complaint.py, openprocurement/tender/openeu/views/qualification_complaint_document.py, openprocurement/tender/openeu/views/qualification_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/47)
=> Validators update

buildout.cfg, openprocurement/tender/openeu/tests/auth.ini, openprocurement/tender/openeu/tests/award.py, openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/tests/tender.py, openprocurement/tender/openeu/views/qualification_document.py
Додали можливість завантажувати документи ботом, до кваліфікацій, для competitiveDialogueUA, competitiveDialogueEU, competitiveDialogueEU.stage?, aboveThresholdEU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/46)
=> Edr integration

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/48)
=> change production to edr_integration

openprocurement/tender/openeu/adapters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/50)
=> Add constants to configurator

openprocurement/tender/openeu/validation.py, openprocurement/tender/openeu/views/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/52)
=> Update bid view validator

buildout.cfg, docs.py, docs/source/tutorial.rst, openprocurement/tender/openeu/models.py, openprocurement/tender/openeu/tests/bid.py, openprocurement/tender/openeu/views/bid_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/56)
=> a258001251842880 add batch mode to refactoring

openprocurement/tender/openeu/tests/award.py, openprocurement/tender/openeu/tests/cancellation.py, openprocurement/tender/openeu/tests/document.py, openprocurement/tender/openeu/tests/question.py, openprocurement/tender/openeu/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/57)
=> A282953159619251 Basic abstract classes for tests

openprocurement/tender/openeu/views/bid.py, openprocurement/tender/openeu/views/qualification_complaint_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/61)
=> Add raise error_handler

openprocurement/tender/openeu/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/62)
=> Update imports in models (SifterListType class)

openprocurement/tender/openeu/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/64)
=> Remove extra function and update imports

openprocurement/tender/openeu/tests/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/59)
=> base classes for award tests

buildout.cfg, openprocurement/tender/openeu/tests/bid.py, openprocurement/tender/openeu/tests/bid_blanks.py, openprocurement/tender/openeu/tests/chronograph.py, openprocurement/tender/openeu/tests/chronograph_blanks.py, openprocurement/tender/openeu/tests/question.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/63)
=> A282953159619251 changes for competitive.dialogue compatibility

openprocurement/tender/openeu/tests/complaint.py, openprocurement/tender/openeu/tests/lot.py, openprocurement/tender/openeu/tests/lot_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/65)
=> added mixin; added features values; added test_author to work with CD

openprocurement/tender/openeu/tests/auction.py, openprocurement/tender/openeu/tests/base.py, openprocurement/tender/openeu/tests/lot.py, openprocurement/tender/openeu/tests/lot_blanks.py
change statuses identifiers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/69)
=> add inline comments for statuses

openprocurement/tender/openeu/tests/tender.py, openprocurement/tender/openeu/tests/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/73)
=> Add test_bids_data attribute to TenderResourceTest

openprocurement/tender/openeu/tests/lot_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/74)
=> Update data for bid value and lotValues in TenderLotProcessTest

buildout.cfg, openprocurement/tender/openeu/tests/auth.ini, openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/tests/qualification_blanks.py, openprocurement/tender/openeu/views/qualification_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/75)
=> A346808780435667 edr integration on refactoring

openprocurement/tender/openeu/tests/award.py, openprocurement/tender/openeu/tests/award_blanks.py, openprocurement/tender/openeu/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/70)
=> Update award tests

openprocurement/tender/openeu/tests/tender.py, openprocurement/tender/openeu/tests/tender_blanks.py
fix import/snitch error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/76)
=> add attribute 'test_bids_values'

openprocurement/tender/openeu/tests/lot_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/77)
=> replace hardcoded values by TestCase attribute

openprocurement/tender/openeu/tests/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/79)
=> replace hardcoded bid values in tender unit tests

openprocurement/tender/openeu/tests/cancellation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/80)
=> move helper methods of  to separate class

openprocurement/tender/openeu/tests/bid_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/81)
=> replace hardcoded values by TestCase attributes

openprocurement/tender/openeu/tests/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/82)
=> rename test mixin

openprocurement/tender/openeu/tests/complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/83)
=> rename blank test

openprocurement/tender/openeu/tests/chronograph.py, openprocurement/tender/openeu/tests/chronograph_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/84)
=> A282953159619251 tests refactoring

buildout.cfg, openprocurement/tender/openeu/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/85)
=> A362908003690022 block cpv on refactoring

openprocurement/tender/openeu/tests/base.py, openprocurement/tender/openeu/tests/contract.py, openprocurement/tender/openeu/tests/contract_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/89)
=> Auth typo fix

buildout.cfg, openprocurement/tender/openeu/utils.py, openprocurement/tender/openeu/views/cancellation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/90)
=> A431278519093170 awarding criteria field

buildout.cfg, docs/source/complaints.rst, openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/tests/qualification_blanks.py, openprocurement/tender/openeu/views/qualification_complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/94)
=> reviewer status transition stopping->satisfied, pending->stopped

openprocurement/tender/openeu/tests/tender_blanks.py
Move logic into separate def.
So we can import this logic from another packeges.(esco)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/95)
=> Add test for invalid tender period

openprocurement/tender/openeu/tests/auction.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/97)
=> add tests awarding with features

openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/tests/qualification_blanks.py, openprocurement/tender/openeu/tests/tender_blanks.py, openprocurement/tender/openeu/views/qualification.py
More info CBD-1713
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/101)
=> Fix set_bid_status bug in qualification view.

openprocurement/tender/openeu/tests/qualification.py, openprocurement/tender/openeu/tests/qualification_blanks.py, openprocurement/tender/openeu/tests/tender_blanks.py, openprocurement/tender/openeu/views/qualification.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/103)
=> Fix set_bid_status bug

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/105)
=> A563879808284502 disable 999999 9 additional classification required

.travis.yml, buildout.cfg, openprocurement/tender/openeu/tests/auction_blanks.py, openprocurement/tender/openeu/tests/bid_blanks.py, openprocurement/tender/openeu/tests/cancellation.py, openprocurement/tender/openeu/tests/cancellation_blanks.py, openprocurement/tender/openeu/tests/lot_blanks.py, openprocurement/tender/openeu/tests/qualification_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/107)
=> Frameworks tests

openprocurement/tender/openeu/tests/bid_blanks.py, openprocurement/tender/openeu/tests/cancellation.py, openprocurement/tender/openeu/tests/cancellation_blanks.py, openprocurement/tender/openeu/tests/qualification_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/106)
=> Refactoring tests for min number of bids

openprocurement/tender/openeu/tests/auction_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/109)
=> Fix for over 3 bids

openprocurement/tender/openeu/tests/award_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/110)
=> Update award logic to handle more than 3 bids

.travis.yml, buildout.cfg, openprocurement/tender/openeu/tests/auction_blanks.py, openprocurement/tender/openeu/tests/award_blanks.py, openprocurement/tender/openeu/tests/bid_blanks.py, openprocurement/tender/openeu/tests/cancellation.py, openprocurement/tender/openeu/tests/cancellation_blanks.py, openprocurement/tender/openeu/tests/lot_blanks.py, openprocurement/tender/openeu/tests/qualification_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/108)
=> A736221711930801 frameworkagreement test fixes

openprocurement/tender/openeu/tests/award_blanks.py, openprocurement/tender/openeu/tests/cancellation_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openeu/111)
=> Modify test due multiple bids
